# Config (CORINE only, WDPA onshore, DC offwind).

start_year: 1982
end_year: 2016
cutout_dir: '//IIP-COMP103/endata/MA_Lisa/atlite_cutouts/cutouts'
out_dir: 'Y:/Group_SEM/MA_Eric/Dissertation/pypsa/opf/renewables/atlite_copy/corine_luisa_wdpa_onoff_acdc'

resources:
  - pv
  - onwind
  - offwind

mask_onshore: true
mask_offshore: true
use_excluder_mask: true
excluder_res_onshore: 100
excluder_res_offshore: 200

onshore_mask_shapes:
  - 'Y:\Group_SEM\MA_Eric\Dissertation\pypsa\opf\datashapes\europe_shape.geojson'
offshore_mask_shapes:
  - 'Y:\Group_SEM\MA_Eric\Dissertation\pypsa\opf\datashapes\eez_offshore_eu27_uk_no_europe_only.geojson'
onshore_regions: 'Y:\Group_SEM\MA_Eric\Dissertation\pypsa\opf\datashapes\regions_onshore_bus_2030_voronoi.geojson'
offshore_regions: 'Y:\Group_SEM\MA_Eric\Dissertation\pypsa\opf\datashapes\eez_offshore_eu27_uk_no_europe_only.geojson'

landuse_dataset: both
landuse_fusion: prefer-luisa
corine_landcover_path: 'Y:\Group_SEM\MA_Eric\Dissertation\pypsa\opf\datashapes\CORINE_LANDCOVER_U2018_CLC2018_V2020_20u1.tif'
luisa_landcover_path: 'Y:\Group_SEM\MA_Eric\Dissertation\pypsa\opf\datashapes\LUISA_basemap_020321_100m.tif'

pypsa_defaults: true
pypsa_offwind_variant: acdc
#min_shore_distance: 30000
max_shore_distance: 150000

exclude_wdpa_offshore: true
exclude_wdpa_onshore: true

shipdensity_threshold: 2.1e7

availability_mode: raster
resource_class_mode: global
resource_classes: 30
resource_class_year: 1982

# Clip CF values below this threshold to zero (PV/onwind/offwind CFs).
clip_p_max_pu: 0.01

capacity_per_sqkm_pv: 5.5
capacity_per_sqkm_onwind: 3.5
capacity_per_sqkm_offwind: 2.25

onwind_turbine: 'Enercon_E126_7500kW'
offwind_turbine: 'Vestas_V164_7MW_offshore'
